#:schema https://mise.en.dev/schema/mise.json
min_version = "2026.5.0"

[settings]
lockfile = true

[tools]
go = "1.26.2"
actionlint = "latest"
goreleaser = "latest"
cosign = "latest"
zizmor = "latest"
rumdl = "latest"
hk = "latest"
pkl = "latest"
shellcheck = "latest"

[env]
HK_MISE = 1
MODULE = "github.com/matcra587/slack-cli"
BINARY_NAME = "slack"
DIST_DIR = "./dist"
GOOS = "{{ exec(command='go env GOOS') }}"
GOARCH = "{{ exec(command='go env GOARCH') }}"

[task_config]
includes = ["tasks.toml"]
