---
name: ci

on:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions: {}

jobs:
  go-ci:
    name: Go CI
    # @clover: constraint=major tag-prefix=go-ci/ tags=actions
    uses: matcra587/github-actions/.github/workflows/go-ci.yml@9e87045cb838afd0d6a65ebff3ae2d50fa7e8887 # go-ci/v0.3.2
    permissions:
      contents: read
    with:
      # clover: provider=github repository=golangci/golangci-lint constraint=major
      golangci-version: v2.13.2

  md-lint:
    name: Markdown lint
    # @clover: constraint=major tag-prefix=go-ci/ tags=actions
    uses: matcra587/github-actions/.github/workflows/md-lint.yml@9e87045cb838afd0d6a65ebff3ae2d50fa7e8887 # go-ci/v0.3.2
    permissions:
      contents: read
